### ISSUE TITLE
It seems that the bdd_daytime.zip compressed file you provided is damaged and cannot be decompressed.

### ISSUE THREAD

**Issue by luoh226** [CityU-AIM-Group/SOMA#1]
![image](https://github.com/CityU-AIM-Group/SOMA/assets/63135179/c876b782-cdff-40b0-a997-2ba83e698bb6)

**Comment by wymanCV** [comment]
Thanks for your interest in our work!

I will have a check as soon as possible. Maybe you can try other datasets, e.g., C2F, at first.  Thanks!

**Comment by luoh226** [comment]
Thank you for your perfect work and prompt reply. I will try C2F.

**Comment by wymanCV** [comment]
Sorry for the inconvenience. 

I found that the bdd100k images are not compressed successfully due to the large scale, while the labels are correct. The images can be downloaded via the official link, and I just updated the readme.

If you can't download the image from the official link, please feel free to reach me by e-mail, and I'll look for other ways to send you the data. 

The data settings are consistent with existing DAOD works, such as [SIGMA](https://github.com/CityU-AIM-Group/SIGMA) and [AQT](https://github.com/weii41392/AQT), and the only difference lies in using VOC format labels to ensure the consistency with existing Open-set/world object detection evaluation

**Comment by luoh226** [comment]
Thanks for the update! I have successfully downloaded the images and labels of the bdd dataset through your updated link.

**Comment by wymanCV** [comment]
I am so so so sorry for the big mistake I made when I cleaned my code,  which will lead to significantly different results with our paper.  I just noticed that due to an issue in terms of the reproducibility.  I have updated the code and tell the reason in ReadMe. I'm very sorry for wasting your energy because of my mistake.

@luoh226
