### ISSUE TITLE
我的复现结果无法达到论文指标，请作者能给我一些帮助。

### ISSUE THREAD

**Issue by Luhui-Zhao** [CityU-AIM-Group/SOMA#5]
作者您好，我是中国地质大学（武汉）的一名在读研究生，在2023年末的时候我看了你的SOMA这篇论文，我对于您的文章很感兴趣，所以便使用您的代码进行复现，在cityscapes2foggy数据集上，我在两片3090显卡上跑了您设置的四个实验，但是四个实验的最终结果都与您论文中的结果有较大差别。同时，我在西安电子科技大学的一名同学也复现了您的实验，他使用了两片V100显卡，但是实验结果也和您的有差别，和我的实验结果倒是很相似。我在复现您代码的过程中，刚开始是按照您的参数进行复现的，但是无法复现您的结果，后来我就自己调参，但是也是无法复现您的结果，下面是我的复现结果，请您查看，如果可以的话，我希望您可以针对我的结果给我提供一些帮助，再次感谢您！
![SOMA实验结果（（截止24 02 26））_01](https://github.com/CityU-AIM-Group/SOMA/assets/133850573/d92c78a2-030d-4ca7-9c87-61324f780f27)

**Comment by wymanCV** [comment]
您好，非常感谢对于我们工作的关注。

根据您复现的结果，AOSE这个指标比我们的好很多（表示错检的unknown 类少很多），而其他指标比较差，对此我也比较困惑 （特别是有些设定的ARn和AOSE都比我们的好），您可以尝试跑下OW-DETR看看是否相似，以判断是否是数据设置等问题造成的。

另外可以通过通过邮件发送给我您的training log，我看看能不能帮上您。

也可以加我的微信: 17720031102

**Comment by kutieling** [comment]
好的，谢谢您的回复，我按照您的思路先去复现一下OW-DETR，同时我添加一下您的微信，后续遇到一些我解决不了的问题时，还需要向您请教，再次感谢您。

**Comment by Luhui-Zhao** [comment]
> 好的，谢谢您的回复，我按照您的思路先去复现一下OW-DETR，同时我添加一下您的微信，后续遇到一些我解决不了的问题时，还需要向您请教，再次感谢您。

好的，谢谢您的回复，我按照您的思路先去复现一下OW-DETR，同时我添加一下您的微信，后续遇到一些我解决不了的问题时，还需要向您请教，再次感谢您。

**Comment by wymanCV** [comment]
Thank you so so much for your issue!!! Thank you so much for your assistance to help me find the mistake.

I am so so so sorry for the big mistake I made when I cleaned my code, which will lead to significantly different results with our paper. I just noticed that due to an issue in terms of the reproducibility. I have updated the code and told the reason in ReadMe. I'm very sorry for wasting your energy because of my mistake.
